CREATE DATABASE IF NOT EXISTS Locacao_Bicicletas CHARACTER SET utf8 collate utf8_bin;
USE Locacao_Bicicletas;

CREATE TABLE IF NOT EXISTS usuario (
  id BIGINT AUTO_INCREMENT NOT NULL,
  email VARCHAR(256) UNIQUE NOT NULL,
  senha VARCHAR(256) NOT NULL,
  nome VARCHAR(110) NOT NULL,
  administrador CHAR(1) DEFAULT "0",
  tipo_usuario CHAR(1) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS cliente (
  id_usuario BIGINT NOT NULL,
  CPF CHAR(11) NOT NULL,
  telefone VARCHAR(20) NOT NULL,
  sexo CHAR(1) NOT NULL,
  data_nascimento DATE NOT NULL,
  PRIMARY KEY (CPF),
  FOREIGN KEY (id_usuario) REFERENCES usuario (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS locadora (
  id_usuario BIGINT NOT NULL,
  CNPJ CHAR(14) NOT NULL,
  cidade VARCHAR(110) NOT NULL,
  PRIMARY KEY (CNPJ),
  FOREIGN KEY (id_usuario) REFERENCES usuario (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS locacao (
  CPF CHAR(11) NOT NULL,
  CNPJ CHAR(14) NOT NULL,
  dia DATE NOT NULL,
  horario TIME NOT NULL,
  PRIMARY KEY (CNPJ, dia, horario),
  FOREIGN KEY (CPF) REFERENCES cliente (CPF) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (CNPJ) REFERENCES locadora (CNPJ) ON DELETE CASCADE ON UPDATE CASCADE
);